# Generated by Django 4.2.7 on 2023-12-16 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cancerpredictor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("radius", models.FloatField()),
                ("texture", models.FloatField()),
                ("perimeter", models.FloatField()),
                ("area", models.FloatField()),
                ("smoothness", models.FloatField()),
                ("compactness", models.FloatField()),
                ("concavity", models.FloatField()),
                ("concave_points", models.FloatField()),
                ("symmetry", models.FloatField()),
                ("fractal_dimension", models.FloatField()),
                ("res", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
